const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){const handlers={},storage={},sent=[],urls=[],timers=[];const c={module:{exports:{}},require:p=>require('../src/pkjs/'+p),console,localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v},setTimeout:f=>{timers.push(f);return timers.length},clearTimeout:()=>{},Pebble:{addEventListener:(n,f)=>handlers[n]=f,sendAppMessage:(m,ok,fail)=>sent.push({m,ok,fail}),openURL:u=>urls.push(u)}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/pkjs/index.js'),'utf8'),c);return {handlers,storage,sent,urls,timers,api:c.module.exports};}
test('ready asks watch and never resets a saved watch',()=>{let h=harness();h.handlers.ready();assert.equal(h.sent[0].m.REQUEST,1);assert.equal(h.sent[0].m.SYSTEM,undefined)});
test('invalid settings never send',()=>{let h=harness();for(const system of [-1,29,1.5,'2'])h.api.choose({system,seconds:1});assert.equal(h.sent.length,0)});
test('preference saves after matching watch acknowledgement',()=>{let h=harness();h.api.choose({system:8,seconds:0});h.handlers.appmessage({payload:{ACK_SYSTEM:0,ACK_SECONDS:1}});assert.equal(Object.keys(h.storage).length,0);h.handlers.appmessage({payload:{ACK_SYSTEM:8,ACK_SECONDS:0}});assert.equal(JSON.parse(h.storage['numerals.settings.v1']).system,8)});
test('changes serialize and stale acknowledgements do not overwrite',()=>{let h=harness();h.api.choose({system:4,seconds:1});h.api.choose({system:8,seconds:0});assert.equal(h.sent.length,1);h.sent[0].ok();assert.equal(h.sent[1].m.SYSTEM,8);h.handlers.appmessage({payload:{ACK_SYSTEM:4,ACK_SECONDS:1}});assert.equal(Object.keys(h.storage).length,0)});
test('cancel preserves settings',()=>{let h=harness();h.handlers.webviewclosed({response:'CANCELLED'});h.handlers.webviewclosed({response:''});assert.equal(h.sent.length,0)});
test('offline attempts bounded',()=>{let h=harness();h.api.choose({system:2,seconds:1});for(let i=0;i<4;i++){h.sent[i].fail();if(h.timers[i])h.timers[i]();}assert.equal(h.sent.length,4)});
test('configuration contains all systems and reading guides',()=>{let h=harness();h.handlers.showConfiguration();let page=decodeURIComponent(h.urls[0].split(',').slice(1).join(','));assert.match(page,/Yautja/);assert.match(page,/Braille/);assert.match(page,/Hours and minutes/);assert.match(page,/source’s decimal adaptation/)});

test("missing watch acknowledgement retries without claiming saved",()=>{let h=harness();h.api.choose({system:8,seconds:0});for(let i=0;i<4;i++){h.sent[i].ok();if(h.timers[i])h.timers[i]();}assert.equal(h.sent.length,4);assert.equal(Object.keys(h.storage).length,0)});
