// Copyright 2026 Luke Steuber. MIT.
var SYSTEMS=require('./systems'),desired=null,inFlight=false,retries=0,timer=null,KEY='numerals.settings.v1';
function valid(s){return s&&typeof s.system==='number'&&s.system%1===0&&s.system>=0&&s.system<SYSTEMS.length&&(s.seconds===0||s.seconds===1);}
function saved(){try{var x=JSON.parse(localStorage.getItem(KEY));if(valid(x))return x;}catch(e){}return {system:0,seconds:1};}
function store(x){try{localStorage.setItem(KEY,JSON.stringify(x));}catch(e){console.log('Phone settings could not be saved.');}}
function retry(snapshot){if(desired!==snapshot)return;if(retries++<3){timer=setTimeout(send,500*retries);}else console.log('Watch has not confirmed these settings; reconnect and save again.');}
function send(){if(inFlight||!desired)return;inFlight=true;var snapshot=desired;Pebble.sendAppMessage({SYSTEM:snapshot.system,SECONDS:snapshot.seconds},function(){inFlight=false;if(desired!==snapshot){retries=0;send();}else retry(snapshot);},function(){inFlight=false;if(desired!==snapshot){retries=0;send();}else retry(snapshot);});}
function choose(s){if(!valid(s))return;desired={system:s.system,seconds:s.seconds};retries=0;if(timer)clearTimeout(timer);send();}
Pebble.addEventListener('ready',function(){Pebble.sendAppMessage({REQUEST:1});});
Pebble.addEventListener('appmessage',function(e){var p=e.payload||{},s={system:p.ACK_SYSTEM,seconds:p.ACK_SECONDS};if(!valid(s))return;if(desired){if(s.system!==desired.system||s.seconds!==desired.seconds)return;desired=null;if(timer)clearTimeout(timer);}store(s);});
Pebble.addEventListener('showConfiguration',function(){
 var s=desired||saved(),options=SYSTEMS.map(function(x){return '<option value="'+x.id+'"'+(x.id===s.system?' selected':'')+'>'+x.name+'</option>';}).join('');
 var guide=JSON.stringify(SYSTEMS).replace(/</g,'\\u003c');
 var html='<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Numerals</title><style>body{font:18px/1.5 system-ui;max-width:30em;margin:auto;padding:24px;color:#171717;background:#fff}select,button{display:block;width:100%;font:inherit;padding:14px;margin:8px 0 24px}button{background:#171717;color:white;border:0;border-radius:6px}:focus-visible{outline:3px solid #007b93;outline-offset:3px}</style><h1>Numerals</h1><label for="system">Numeral system</label><select id="system">'+options+'</select><label for="seconds">Time groups</label><select id="seconds"><option value="1"'+(s.seconds?' selected':'')+'>Hours, minutes, seconds</option><option value="0"'+(!s.seconds?' selected':'')+'>Hours and minutes</option></select><p id="guide"></p><p>Hours use 0–23 in local time. Your choice is saved on the watch. Showing hours and minutes updates once per minute.</p><button id="save">Save to watch</button><p>Luke Steuber · Ambient Time</p><script>var systems='+guide+';function explain(){var s=systems[Number(document.getElementById("system").value)];document.getElementById("guide").textContent=s.guide;}document.getElementById("system").onchange=explain;explain();document.getElementById("save").onclick=function(){location.href="pebblejs://close#"+encodeURIComponent(JSON.stringify({system:Number(document.getElementById("system").value),seconds:Number(document.getElementById("seconds").value)}))};<\/script></html>';
 Pebble.openURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));
});
Pebble.addEventListener('webviewclosed',function(e){if(!e.response||e.response==='CANCELLED')return;try{choose(JSON.parse(decodeURIComponent(e.response)));}catch(error){console.log('Settings were not changed.');}});
if(typeof module!=='undefined')module.exports={valid:valid,saved:saved,choose:choose};
