"""Pack hash-verified native samples for offline phone settings."""
from pathlib import Path
import base64
import hashlib
import json
import struct

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'reference/settings-previews'
manifest = json.loads((source / 'manifest.json').read_text())
systems = json.loads((ROOT / 'systems.json').read_text())
dimensions = {'basalt': (144, 168), 'diorite': (144, 168), 'emery': (200, 228), 'flint': (144, 168)}
frames = {platform: [[None, None] for _ in systems] for platform in dimensions}
images, indices = [], {}
for frame in manifest['frames']:
    data = (source / frame['file']).read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    assert digest == frame['sha256']
    assert data[:8] == b'\x89PNG\r\n\x1a\n'
    assert struct.unpack('>II', data[16:24]) == dimensions[frame['platform']]
    if digest not in indices:
        indices[digest] = len(images)
        images.append('data:image/png;base64,' + base64.b64encode(data).decode('ascii'))
    group = frames[frame['platform']][frame['system']]
    assert group[frame['seconds']] is None
    group[frame['seconds']] = indices[digest]
assert all(index is not None for platform in frames.values() for row in platform for index in row)
payload = {'images': images, 'frames': frames}
(ROOT / 'src/pkjs/previews.js').write_text(
    '// Generated by tools/generate-previews.py from verified native samples.\n'
    + 'module.exports=' + json.dumps(payload, separators=(',', ':')) + ';\n')
print(len(manifest['frames']), 'native previews;', len(images), 'unique images')
