"""Pack source sign bitmaps into bounded independent LZSS blocks."""
from pathlib import Path
import json,struct,hashlib
ROOT=Path(__file__).resolve().parents[1]
rows=json.loads((ROOT/'build/art/manifest.json').read_text())
COLORS=[('000000','ffffff'),('ffffaa','555500'),('ffffaa','aa0000'),('000000','ffffaa'),('ffaa55','550000'),('ffffaa','550000'),('ffffaa','550000'),('000000','ffffff'),('000000','55ffaa'),('000000','00ffaa'),('ffaa55','550000'),('000000','ff5555'),('550000','ffffaa'),('000000','55ff55'),('000000','aaff55'),('ffffaa','000000'),('000000','00ffff'),('000000','aa55ff'),('000000','aa55ff'),('000000','55ffaa'),('000000','55aaff'),('000000','aaff55'),('000000','ffaa00'),('ffffaa','000000'),('000000','aa55ff'),('ffffaa','aa0000'),('000000','55aaff'),('000000','ff5555'),('000000','ffaa00')]
def pack(data):
 out=bytearray();i=0
 while i<len(data):
  flagpos=len(out);out.append(0);flags=0
  for bit in range(8):
   if i==len(data):break
   found=-1;length=0
   for n in range(min(18,len(data)-i),2,-1):
    at=data.rfind(data[i:i+n],max(0,i-4096),i+n-1)
    if at>=0:found=at;length=n;break
   if found>=0:
    out.extend(struct.pack('<H',((i-found-1)<<4)|(length-3)));i+=length
   else:flags|=1<<bit;out.append(data[i]);i+=1
  out[flagpos]=flags
 return bytes(out)
header=['// Generated by tools/pack-art.py. Copyright 2026 Luke Steuber.','#pragma once','#define SYSTEM_COUNT '+str(len(rows)),'typedef struct { uint8_t width,height,columns,dark; uint32_t background,ink; } NumeralStyle;','static const NumeralStyle STYLES[]={']
manifest=[]
for r,(bg,fg) in zip(rows,COLORS):
 data=(ROOT/'build/art'/f"{r['slug']}.raw").read_bytes();stride=r['rawBytes'];chunks=[pack(data[n*stride:(n+1)*stride]) for n in range(60)];offset=360;index=bytearray()
 for b in chunks:index.extend(struct.pack('<IH',offset,len(b)));offset+=len(b)
 dest=ROOT/'resources'/f"{r['slug']}.bin";dest.write_bytes(index+b''.join(chunks));dark=int(bg in ['000000','550000']);header.append('{%d,%d,%d,%d,0x%s,0x%s},'%(r['width'],r['height'],r['layout']=='columns',dark,bg,fg))
 manifest.append({k:r[k] for k in ['id','slug','name','sourceSHA256','layout','width','height'] }|{'sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'bytes':dest.stat().st_size,'maxBlock':max(map(len,chunks)),'rawBytes':stride,'distinctValues':60})
header.extend(['};','static const uint32_t RESOURCES[]={'+','.join('RESOURCE_ID_NUMERAL_'+str(r['id']) for r in rows)+'};']);(ROOT/'src/c/styles.h').write_text('\n'.join(header)+'\n');(ROOT/'reference/art-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print(len(rows),'systems;',sum(x['bytes'] for x in manifest),'resource bytes; max compressed block',max(x['maxBlock'] for x in manifest))

systems=json.loads((ROOT/"systems.json").read_text())
(ROOT/"src/pkjs/systems.js").write_text("// Generated by tools/pack-art.py.\nmodule.exports="+json.dumps([{k:r[k] for k in ["id","name","guide","layout"]} for r in systems],ensure_ascii=False)+";\n")
